apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/server-snippet: "server_tokens off;"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-rpm: "300"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    # ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/24,172.10.0.1"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/cluster-issuer: "hiamt9a-cert"
spec:
  ingressClassName: "nginx"
  # tls:
  #   - hosts:
  #       - hiamt9a.io.vn
  #     secretName: hiamt9a-cert
    
  rules:
    - host: hiamt9a.io.vn
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway-clusterip-srv
                port:
                  number: 1000
          - path: /socket.io(/|$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: socket-server-clusterip-srv
                port:
                  number: 1005
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-app-chat-serv
                port:
                  number: 3000
    - host: logging.hiamt9a.io.vn
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kibana
                port:
                  number: 5601
    - host: distribute-tracing.hiamt9a.io.vn
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
    # - host: k8s-dashboard.hiamt9a.io.vn
    #   http:
    #     paths:
    #       - path: /(.*)
    #         pathType: ImplementationSpecific
    #         backend:
    #           service:
    #             name: kubernetes-dashboard
    #             port:
    #               number: 8000
          
