apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: hiamt34/auth-server-app-chat
          env:
            - name: PORT_AUTH_SEVER
              value: "1001"
            - name: HOST_AUTH_SEVER
              value: "0.0.0.0"
            - name: PORT_MES_SEVER
              value: "1004"
            - name: HOST_MES_SEVER
              value: "mes-server-clusterip-srv"
            - name: PORT_ROOM_SEVER
              value: "1003"
            - name: HOST_ROOM_SEVER
              value: "room-server-clusterip-srv"
            - name: PORT_USER_SEVER
              value: "1002"
            - name: HOST_USER_SEVER
              value: "user-server-clusterip-srv"
            - name: HOST_REDIS
              value: "redis-clusterip-srv"
            - name: PRIVATE_KEY
              value: "HIAMT34"
            - name: GENSALTBCRYPT
              value: "12"
            - name: ACCESS_TOKEN_LIFE_RD
              value: "86400"
            - name: REFRESH_TOKEN_LIFE_RD
              value: "2592000"
            - name: ACCESS_TOKEN_LIFE
              value: "1d"
            - name: REFRESH_TOKEN_LIFE
              value: "30d"
            - name: SERVERNAME
              value: "auth-server"
          ports:
            - containerPort: 1001
          volumeMounts:
            - name: log
              mountPath: /usr/src/app/logs
        - name: filebeat
          image: elastic/filebeat:7.16.3
          args:
            - -c
            - /etc/filebeat/conf.yaml
            - -e
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
    - name: auth-server-clusterip
      protocol: TCP
      port: 1001
      targetPort: 1001
