apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    component: filebeat
data:
  conf.yaml: |
    filebeat.inputs:
    - type: log
      paths:
        - '/var/log/*.log'
    output:
      logstash:
        hosts: [ "logstash:5044" ]

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: filebeat-config
#   labels:
#     component: filebeat
# data:
#   conf.yaml: |
#     filebeat.inputs:
#     - type: log
#       paths:
#         - '/var/log/*.log'
#       fields:
#         filebeat_name: "filebeat-instance-1"
#       fields_under_root: true
#     output:
#       logstash:
#         hosts: ["logstash:5044"]