apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.16.3
          ports:
            - containerPort: 5601
          env:
          - name: "ELASTICSEARCH_USERNAME"
            value: "kibana_system"
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: elasticsearch-passwords
                key: kibana_system
          - name: "ELASTICSEARCH_HOSTS"
            value: "http://elasticsearch:9200"
          - name: "XPACK_SECURITY_ENCRYPTIONKEY"
            value: "YHODxp265VMIfqkYMQepGYIM8kLTjvvAOF2mgRAhd20="
          - name: "XPACK_REPORTING_ENCRYPTIONKEY"
            value: "YHODxp265VMIfqkYMQepGYIM8kLTjvvAOF2mgRAhd20="
          - name: "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY"
            value: "YHODxp265VMIfqkYMQepGYIM8kLTjvvAOF2mgRAhd20="
      nodeSelector:
        nodeWorker: slave1

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  type: NodePort
  ports:
    - name: kibana-nodeport
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 31601
  selector:
    component: kibana
