apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-passwords
type: Opaque
data:
  elastic: NXBINDhOT0c2andOY0xueE9HZEM= #<mật_khẩu_elastic_dưới_dạng_base64>
  kibana_system: ZWlpQmlqWFh4Tk9oOTBvaGM3R2g= #<mật_khẩu_kibana_system_dưới_dạng_base64> -> phai bash vao elastic de lay password