apiVersion: apps/v1
kind: Deployment
metadata:
    name: jaeger
    labels:
        app: jaeger
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jaeger
    template:
        metadata:
            labels:
                app: jaeger
        spec:
            containers:
                - name: jaeger
                  image: jaegertracing/all-in-one:1.47
                  ports:
                      - containerPort: 6831
                        protocol: UDP
                      - containerPort: 6832
                      - containerPort: 5778
                      - containerPort: 16686
                      - containerPort: 14250
                      - containerPort: 14268
                      - containerPort: 14269
                      - containerPort: 9411
                  env:
                      - name: COLLECTOR_ZIPKIN_HOST_PORT
                        value: ':9411'
                      - name: COLLECTOR_OTLP_ENABLED
                        value: 'true'
                      - name: SPAN_STORAGE_TYPE
                        value: 'elasticsearch'
                      - name: ES_SERVER_URLS
                        value: 'http://elasticsearch:9200'
---
apiVersion: v1
kind: Service
metadata:
    name: jaeger
    labels:
        app: jaeger
spec:
    ports:
        - name: udp
          port: 6831
          protocol: UDP
        - name: compact
          port: 6832
        - name: binary
          port: 5778
        - name: http-query16686
          port: 16686
        - name: http-collector
          port: 14268
        - name: admin-http
          port: 14269
        - name: http-collector-9411
          port: 9411
    selector:
        app: jaeger
